# the messages that will print to the console
action = ("What movement would you like to do? ")
congrats = ("CONGRATULATIONS!! ")
coll = ("Do you want to collect it? ")
answer = ("Sounds good ")
error = ("Please only answer yes or no. No capitall letters. ")
hint = ("Would you like a hint for the puzzle? ")
clueOrder1 = ("You could try putting the first 3 in order first. ")
clueOrder2 = ("After putting the first 3 in order, you should get CAB. Where should D and E go? ")
errorclue = ("No capital letters. Just inpur the answer. ")
puzzle = ("What is the answer to this lock? ")
answerpuzzle = ("That is not the right answer. Please try a different one. ")
lock = ("This is the puzzle you need to solve in order to escape this room: ")
clueDay1 = ("The 'day before tomorrow' is today. ")