# the messages that will print to the console
action = ("What movement would you like to do? ")
actionFinish = ("Your action is finished. ")
congrats = ("CONGRATULATIONS!! ")
coll = ("Do you want to collect it? ")
answer = ("Sounds good ")
error = ("Please only answer yes or no. No capitall letters. ")
hint = ("Would you like a hint for the puzzle? ")
clueOrder1 = ("You could try putting the first 3 in order first. ")
clueOrder2 = ("After putting the first 3 in order, you should get CAB. Where should D and E go? ")
errorclue = ("No capital letters. Just inpur the answer. ")
puzzle = ("What is the answer to this lock? ")
answerpuzzle = ("That is not the right answer. Please try a different one. No Capital Letters. ")
lock = ("This is the puzzle you need to solve in order to escape this room: ")
clueDay1 = ("The 'day before tomorrow' is today. ")
clueDay2 = ("The 'day before 2 days after' is one day after. So what day is today if one day after today is Satudrday? ")
clueHeight1 = ("Ignore the second part of the description of that person, because it is useless. ")
clueHeight2 = ("If M is the second tallest person here, who is the tallest? ")
clueAlpha1 = ("What is the first alphabet of 1 when written in words ? ")
clueAlpha2 = ("1 = One, 2 = Two, 3 = Three... ")
clueDau1 = ("R, T, S, and A are the mother's four daughters. Who is the fifth one? ")
clueDau2 = ("Whose mother has five daughers? ")
clueRel1 = ("The father of her brother is also her father. ")
clueRel2 = ("The father of her brother means her own father and the only son of my grandfather means my father. ")
clueMon1 = ("Months")
clueMon2 = ("D = December")